RNemch/ya.cats

packages/client/jest.config.js
packages/client/package.json
packages/client/src/app.css
packages/client/src/components/background/index.tsx
packages/client/src/components/background/styles.module.css
packages/client/src/components/button/index.tsx
packages/client/src/components/button/styles.module.css
packages/client/src/components/center/index.tsx
packages/client/src/components/center/styles.module.css
packages/client/src/components/input/index.tsx
packages/client/src/components/input/styles.module.css
packages/client/src/components/paper/index.tsx
packages/client/src/components/paper/styles.module.css
packages/client/src/components/space/index.tsx
packages/client/src/components/typography/index.tsx
packages/client/src/core/types.ts
packages/client/src/index.css
packages/client/src/style/font-size.module.css
packages/client/tsconfig.json
packages/client/vite.config.ts
yarn.lock

fix: components

---

packages/client/jest.config.js
packages/client/src/components/input/styles.module.css
packages/client/src/components/modal/index.tsx
packages/client/src/components/modal/styles.module.css
packages/client/src/components/paper/index.tsx
packages/client/src/components/typography/index.tsx
packages/client/src/components/typography/styles.module.css
packages/client/src/controllers/user-controller.ts
packages/client/src/core/types.ts
packages/client/src/pages/ProfilePage/AvatarUpload/index.tsx
packages/client/src/pages/ProfilePage/AvatarUpload/styles.module.css
packages/client/src/pages/ProfilePage/EditPasswordModalContent/index.tsx
packages/client/src/pages/ProfilePage/EditPasswordModalContent/styles.module.css
packages/client/src/pages/ProfilePage/index.tsx
packages/client/src/pages/ProfilePage/styles.module.css
packages/client/src/services/api.service.ts
packages/client/src/services/http.service.ts
packages/client/src/services/user-api.ts
packages/client/src/types/server-error.ts
packages/client/src/types/user-password-data.ts
packages/client/tsconfig.json
packages/client/vite.config.ts

- Верстка страницы профиля
- Подключено api смены пароля (без авторизации пока выдает ошибку куки, само подключение работает)
- Верстка компонента изменения аватара 
- Подключено api смены аватара (без авторизации выдает ошибку куки)
- Валидацию полей формы или редактирование полей не делала, тк это другие задачи
https://github.com/RNemch/ya.cats/assets/72467978/b8595f56-c4ef-4b37-985f-7258cc99d05e
(инпут на русском тк язык системы русский, он использует язык системы)
- добавила в `Input` отступ между label  и input
- добавила в `Paper` возможность добавлять класс
- добавила для `Typography` белый цвет, чтобы был заголовок модалки как в макете
- ❗️ **добавьте себе в файл .env эндпоинт API_URL=https://ya-praktikum.tech/api/v2**
(он у нас в гитигноре)

feat: profile page

---

.env.sample
packages/client/src/components/protected-route/index.tsx
packages/client/src/controllers/auth-controller.ts
packages/client/src/controllers/user-controller.ts
packages/client/src/core/constants.ts
packages/client/src/core/types.ts
packages/client/src/pages/LoginPage/index.tsx
packages/client/src/pages/MainPage/index.tsx
packages/client/src/pages/ProfilePage/AvatarUpload/index.tsx
packages/client/src/router.tsx
packages/client/src/services/auth-api.ts
packages/client/src/services/http.service.ts
packages/client/src/services/user-api.ts

[Реализовать логику авторизации](https://linear.app/yacats/issue/YAC-16/realizovat-logiku-avtorizacii)
Подключить[ API Практикума](https://ya-praktikum.tech/api/v2/swagger/#/Auth/post_auth_signin) для авторизации пользователя.
Пользователь не может зайти ни на какую страницу проекта, если он не авторизован.

feat: добавлена логика авторизации

---

packages/client/src/pages/MainPage/index.tsx

[Сверстать главную страницу игры: мини-лендинг с презентацией игры](https://linear.app/yacats/issue/YAC-12/sverstat-glavnuyu-stranicu-igry-mini-lending-s-prezentaciej-igry)

feat: ui main page

---

packages/client/src/controllers/auth-controller.ts
packages/client/src/controllers/leaderboard-controller.ts
packages/client/src/controllers/topic-controller.ts
packages/client/src/controllers/user-controller.ts
packages/client/src/main.tsx
packages/client/src/services/api/auth-api.ts
packages/client/src/services/api/leaderboard-api.ts
packages/client/src/services/api/topic-api.ts
packages/client/src/services/api/user-api.ts
packages/client/src/services/sw.service.ts
packages/client/src/utils/register-sw.ts
packages/client/vite.config.ts
packages/server/tsconfig.prod.json

- добавить service worker
https://github.com/RNemch/ya.cats/assets/72467978/44944c64-a208-4202-938f-37f9cbb2a6d6
- сгруппировала все апишки в одной папке

feat: add service worker

---

packages/client/src/pages/GamePage/FullpageButton/index.tsx
packages/client/src/pages/GamePage/FullpageButton/styles.module.css
packages/client/src/pages/GamePage/index.tsx

- добавляет fullscreen api
https://github.com/RNemch/ya.cats/assets/72467978/fdf4e898-df69-42cd-8afd-e73fefa580df

feat: add fullscreen api

---

packages/client/src/mechanics/entities/butterfly.ts
packages/client/src/mechanics/entities/player.ts
packages/client/src/mechanics/screens/game-screen.ts
packages/client/src/mechanics/system/particles.ts
packages/client/src/mechanics/utils/index.ts

Проработать визуальную часть игры
Вместо элементов-заглушек должны быть финальные модели. Фигуры должны быть заменены на персонажей.

feat(animation): add particles, refactoring

---

packages/client/jest.config.js
packages/client/package.json
packages/client/src/app.tsx
packages/client/src/components/protected-route/index.tsx
packages/client/src/components/spinner/index.tsx
packages/client/src/components/spinner/styles.module.css
packages/client/src/controllers/auth-controller.ts
packages/client/src/controllers/user-controller.ts
packages/client/src/core/types.ts
packages/client/src/pages/LoginPage/index.tsx
packages/client/src/pages/MainPage/index.tsx
packages/client/src/pages/ProfilePage/AvatarUpload/index.tsx
packages/client/src/pages/ProfilePage/EditPasswordModalContent/index.tsx
packages/client/src/pages/ProfilePage/index.tsx
packages/client/src/pages/SignupPage/index.tsx
packages/client/src/services/api/auth-api.ts
packages/client/src/services/api/user-api.ts
packages/client/src/services/http.service.ts
packages/client/src/store/hooks.ts
packages/client/src/store/index.ts
packages/client/src/store/user/user-slice.ts
packages/client/src/store/user/user-thunks.ts
packages/client/tsconfig.json
packages/client/vite.config.ts
yarn.lock

[Добавить Redux хранилище](https://linear.app/yacats/issue/YAC-38/dobavit-redux-hranilishe-dannye-hranyatsya-i-obrabatyvayutsya-cherez)

feat: добавлен redux toolkit, слайс для юзера

---

packages/client/src/pages/GamePage/FullpageButton/index.tsx

- фикс бага, когда при выходе из полноэкранного режима при нажатии пробела происходил клик по кнопке
- добавила возможность заходить в полноэкранный режим по 'f'

fix: fullscreen

---

README.md

Добавил ссылку на видео в ритме и убрал некоторые не нужные пункты из него

feat: add url to YouTube in readme

---

packages/client/src/components/modal/index.tsx
packages/client/src/components/modal/styles.module.css
packages/client/src/pages/ProfilePage/AvatarUpload/index.tsx

Добавить крестик для закрытия на модалку

feat(YAC-42): add close button to modal

---

packages/client/src/main.tsx
packages/client/src/services/notification.service.ts
packages/client/src/utils/register-online-status-checker.ts

- добавила notification api. Теперь если у пользователя произошел обрыв соединения, показывается уведомление

feat: add notification api for online/offline

---

packages/client/src/pages/ProfilePage/AvatarUpload/index.tsx
packages/client/src/pages/ProfilePage/AvatarUpload/styles.module.css

[Сделать компонент загрузки аватара более информативным](https://linear.app/yacats/issue/YAC-43/sdelat-komponent-zagruzki-avatara-bolee-informativnym)

fix(AvavtarUpload): add default img and hover

---

packages/client/src/controllers/leaderboard-controller.ts
packages/client/src/core/types.ts
packages/client/src/pages/GamePage/GameOver/index.tsx
packages/client/src/pages/LeaderBoardPage/LeaderBoardTable/TableItem/index.tsx
packages/client/src/pages/LeaderBoardPage/LeaderBoardTable/index.tsx
packages/client/src/services/api/leaderboard-api.ts

[Добавить API для лидерборда](https://linear.app/yacats/issue/YAC-49/dobavit-api-dlya-liderborda)

feat: leaderboard api

---

docker-compose.yml
packages/client/package.json
packages/client/src/components/button/index.tsx
packages/client/src/components/button/styles.module.css
packages/client/src/core/types.ts
packages/client/src/pages/LoginPage/__snapshots__/index.test.tsx.snap
packages/client/src/pages/LoginPage/index.tsx
packages/client/src/pages/LoginPage/styles.module.css
packages/client/src/pages/ProfilePage/index.tsx
packages/client/src/pages/ProfilePage/styles.module.css
packages/client/src/pages/SignupPage/index.tsx
packages/client/src/pages/SignupPage/styles.module.css
yarn.lock

[Серверная инфраструктура для форума, эмодзи и темизации](https://linear.app/yacats/issue/YAC-53/servernaya-infrastruktura-dlya-foruma-emodzi-i-temizacii) и [добавить компонент LinkButton для ссылок с подчеркиванием](https://linear.app/yacats/issue/YAC-44/dobavit-komponent-linkbutton-dlya-ssylok-s-podcherkivaniem)
Так как серверная инфраструктура уже была почти готова, то решил докинуть сюда еще одну задачку

feat: button link and fix docker

---

packages/client/src/services/sw.service.ts

- фиксит неработающее notification api

fix: return index.html url to sw

---

.github/workflows/build_and_push.yml

- добавляет скрипт build_and_push

feat: add build_and_push action

---

packages/server/index.ts
packages/server/middlewares/csp.ts

[YAC-61 Добавить CSP](https://linear.app/yacats/issue/YAC-61/dobavit-csp)

YAC-61 Добавить CSP

---

.env.cloud
.github/workflows/build_and_push.yml

fix: github action build and push

---

packages/client/src/pages/ForumTopicPage/TopicCommentsList/Comment/index.tsx
packages/client/src/pages/ForumTopicPage/TopicCommentsList/Reaction/index.tsx
packages/client/src/services/api/oauth-api.ts
packages/client/src/services/sw.service.ts

fix: oauth, service worker

---

packages/client/src/pages/ForumTopicPage/index.tsx
packages/client/src/routes.tsx
packages/server/tsconfig.json

fix(main): fix ts server lib check, ref
